feature: integrate core app with keycloak
meeteor-13/core pull request #6
Opened 2019-08-18 14:55 UTC by solairerove

2019-08-19 07:58 UTC, alebabai submitted a review, later dismissed

2019-08-19 08:35 UTC, solairerove commented
Но еще глянь саму клоаку. Прежде чем это мердить. Кстати у меня нет прав мердить.

2019-08-19 10:18 UTC, alebabai commented on src/main/resources/application.yml
> +  security:
Please, override this in docker-compose via env using service domain name.

2019-08-19 18:06 UTC, vadim-gleyf submitted a review, later dismissed

2019-08-21 21:28 UTC, alebabai submitted a review, later dismissed

2019-08-22 12:44 UTC, alebabai requested changes
Please, make /actuator/* endpoints open without token

2019-08-23 10:32 UTC, vadim-gleyf approved these changes

2019-08-23 10:34 UTC, vadim-hleif commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +// Thanks spring a lot
типа скопал ?

2019-08-23 10:37 UTC, vadim-gleyf requested changes

2019-08-23 10:37 UTC, vadim-hleif commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +            new UsernamePasswordAuthenticationToken(source.getSubject(), "n/a", authorities);
что такое "n/a"

2019-08-23 10:37 UTC, vadim-hleif commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +            .map(authority -> ROLE_PREFIX + authority.toUpperCase(Locale.getDefault()))
string.format
не справится же тут компилятор, или я не прав?

2019-08-23 10:37 UTC, vadim-hleif commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +            e.printStackTrace();
давай норм хендл, типа если в токене такого нет - кидай что-то, что на 403 маппится
ретурн снизу тоже чекни на налл, вдруг эта нода есть а ролей нет

2019-08-26 14:26 UTC, alebabai approved these changes

2019-08-26 14:39 UTC, alebabai requested changes

2019-08-26 14:39 UTC, alebabai commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +                    .readValue(source.getClaimAsString(RESOURCE_ACCESS_CLAIMS), Map.class)
Зачем обжектмаппер и экскепшн
```java
      source.getClaimAsMap(RESOURCE_ACCESS_CLAIMS)
```

м.б. так ?
```java
        return Optional.ofNullable(source.getClaimAsMap(RESOURCE_ACCESS_CLAIMS))
            .map(it -> ((Map<String, List<String>>) it.get(RESOURCE_ID)))
            .map(map -> map.get(RESOURCE_ROLES_KEY))
            .orElseGet(Collections::emptyList);
```

2019-08-26 14:40 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +// Thanks spring a lot
@vadim-hleif что такое скопал

2019-08-26 14:41 UTC, alebabai commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +// Thanks spring a lot
@solairerove  ctrl + c

2019-08-26 14:41 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +            new UsernamePasswordAuthenticationToken(source.getSubject(), "n/a", authorities);
означает что не надо креды, потому что в жвт их нема

2019-08-26 14:42 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +// Thanks spring a lot
это мои комментарии

2019-08-26 14:43 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +// Thanks spring a lot
@alebabai спецово их тут оставил, чтоб вопросов не было. но походу не помогло

2019-08-26 14:46 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +            .map(authority -> ROLE_PREFIX + authority.toUpperCase(Locale.getDefault()))
зробил стринг формат. залью

2019-08-26 14:48 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +            e.printStackTrace();
а если снизу есть нода но нема ролей, то пофигу в принципе. ну значит нет доступа.

2019-08-26 14:52 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +                    .readValue(source.getClaimAsString(RESOURCE_ACCESS_CLAIMS), Map.class)
согласен

2019-08-26 14:56 UTC, solairerove commented
@vadim-hleif @alebabai залил изменения

2019-08-26 19:09 UTC, alebabai approved these changes

2019-08-27 11:27 UTC, vadim-hleif commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +                    .readValue(source.getClaimAsString(RESOURCE_ACCESS_CLAIMS), Map.class)
чтобы сразу упасть,  может работать с человеком у которого нет ни одной роли? (с токеном что-то не так)

2019-08-27 11:31 UTC, vadim-gleyf requested changes

2019-08-27 11:31 UTC, vadim-hleif commented on src/main/java/com/github/meeteor13/core/controller/LocationController.java
> +    @PreAuthorize("hasRole('LOCATION_READ')")
зачем мы их сразу добавляем? тем более без тестов :)

выпили их все

2019-08-27 11:31 UTC, vadim-hleif commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +        final Collection<GrantedAuthority> authorities = Optional
а нам точно ок что пустой список будет а не просто упадет? ну типа нет ролей, не может ничего смотреть (пока можно и так оставить но давайте тесты еще напишем на код этот)

2019-08-27 11:47 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/controller/LocationController.java
> +    @PreAuthorize("hasRole('LOCATION_READ')")
Один говорит добавь. Второй говорит шо хуйня.

2019-08-27 11:48 UTC, solairerove commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +        final Collection<GrantedAuthority> authorities = Optional
Ну нет ролей к данному ресурсу значит.

2019-08-27 12:52 UTC, alebabai commented on src/main/java/com/github/meeteor13/core/converter/LibraryUserRolesJwtAuthenticationConverter.java
> +        final Collection<GrantedAuthority> authorities = Optional
@vadim-hleif потом в другие сервисы этого код тоже понадобится - вынесем в либу и покроем.
пока можно мержить

2019-08-27 13:08 UTC, vadim-gleyf approved these changes

2019-08-28 08:48 UTC, merged